default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: antenna_weather_development

test:
  <<: *default
  database: antenna_weather_test

production:
  <<: *default
  database: antenna_weather_production
  username: antenna_weather
  password: <%= ENV['ANTENNA_WEATHER_DATABASE_PASSWORD'] %>
